"use client";

import { motion } from "framer-motion";
import {
  ArrowRight,
  Sparkles,
  Target,
  TrendingUp,
  Zap,
  BookOpen,
  Briefcase,
  ChevronRight,
  Award,
} from "lucide-react";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ForgeCoinIcon } from "@/components/ui/coin-animation";
import Link from "next/link";

// ============================================
// Animation Variants
// ============================================

const fadeUp = {
  hidden: { opacity: 0, y: 30 },
  visible: (i: number) => ({
    opacity: 1,
    y: 0,
    transition: { delay: i * 0.1, duration: 0.6, ease: [0.22, 1, 0.36, 1] as const },
  }),
};

const staggerContainer = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: { staggerChildren: 0.12 },
  },
};

const scaleIn = {
  hidden: { opacity: 0, scale: 0.9 },
  visible: {
    opacity: 1,
    scale: 1,
    transition: { duration: 0.5, ease: [0.22, 1, 0.36, 1] as const },
  },
};

// ============================================
// Feature Cards Data
// ============================================

const features = [
  {
    icon: Target,
    title: "AI-Powered Roadmaps",
    description:
      "Get a step-by-step career roadmap generated by AI, personalized to your goals, skills, and experience level.",
    gradient: "from-cyan-500/20 to-blue-500/20",
    iconColor: "text-cyan-accent",
  },
  {
    icon: TrendingUp,
    title: "Progress Tracking",
    description:
      "Visual dashboards with animated progress bars, streak tracking, and skill radar charts to keep you motivated.",
    gradient: "from-purple-500/20 to-pink-500/20",
    iconColor: "text-purple-accent",
  },
  {
    icon: Award,
    title: "Forge Coins & Rewards",
    description:
      "Earn Forge Coins for every milestone, level up from Novice to Forge Master, and unlock exclusive perks along the way.",
    gradient: "from-amber-500/20 to-yellow-500/20",
    iconColor: "text-amber-400",
  },
  {
    icon: Briefcase,
    title: "Market Opportunities",
    description:
      "Discover internships and jobs with AI-calculated match percentages and personalized application insights.",
    gradient: "from-emerald-500/20 to-teal-500/20",
    iconColor: "text-emerald-400",
  },
];

// ============================================
// Landing Page Component
// ============================================

export default function LandingPage() {
  const [targetRole, setTargetRole] = useState("");
  const router = useRouter();

  const handleGenerate = () => {
    if (targetRole.trim()) {
      router.push(`/auth/login?role=${encodeURIComponent(targetRole.trim())}`);
    }
  };

  return (
    <div className="relative min-h-screen overflow-hidden bg-background">
      {/* ============================================
          Background Effects
          ============================================ */}
      <div className="pointer-events-none absolute inset-0">
        {/* Radial gradient glow — top */}
        <div className="absolute -top-[400px] left-1/2 h-[800px] w-[800px] -translate-x-1/2 rounded-full bg-cyan-accent/[0.07] blur-[120px]" />
        {/* Radial gradient glow — bottom left */}
        <div className="absolute -bottom-[300px] -left-[200px] h-[600px] w-[600px] rounded-full bg-purple-accent/[0.05] blur-[100px]" />
        {/* Amber glow — bottom right for rewards feel */}
        <div className="absolute -bottom-[200px] -right-[200px] h-[400px] w-[400px] rounded-full bg-amber-500/[0.03] blur-[80px]" />
        {/* Dot pattern */}
        <div className="absolute inset-0 dot-pattern opacity-40" />
      </div>

      {/* ============================================
          Navigation
          ============================================ */}
      <motion.nav
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="relative z-10 flex items-center justify-between px-6 py-5 md:px-12"
      >
        <Link href="/" className="flex items-center gap-2">
          <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-gradient-to-br from-cyan-accent to-purple-accent">
            <Zap className="h-5 w-5 text-black" />
          </div>
          <span className="text-lg font-bold tracking-tight text-foreground">
            Careerly <span className="text-gradient-cyan">AI</span>
          </span>
        </Link>

        <div className="flex items-center gap-3">
          <Link href="/auth/login">
            <Button
              variant="ghost"
              className="text-muted-foreground hover:text-foreground transition-colors"
            >
              Sign In
            </Button>
          </Link>
          <Link href="/auth/signup">
            <Button className="bg-gradient-to-r from-cyan-accent to-cyan-glow text-black font-semibold hover:opacity-90 transition-opacity">
              Get Started
            </Button>
          </Link>
        </div>
      </motion.nav>

      {/* ============================================
          Hero Section
          ============================================ */}
      <section className="relative z-10 mx-auto flex max-w-5xl flex-col items-center px-6 pt-20 pb-16 text-center md:pt-32 md:pb-24">
        {/* Badge */}
        <motion.div
          initial={{ opacity: 0, scale: 0.8 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.5 }}
          className="mb-8"
        >
          <div className="inline-flex items-center gap-2 rounded-full border border-cyan-accent/20 bg-cyan-accent/[0.06] px-4 py-1.5 text-sm text-cyan-accent">
            <Sparkles className="h-4 w-4" />
            <span>Powered by AI Intelligence</span>
          </div>
        </motion.div>

        {/* Headline */}
        <motion.h1
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, delay: 0.1, ease: [0.22, 1, 0.36, 1] as const }}
          className="text-4xl font-extrabold leading-tight tracking-tight md:text-6xl lg:text-7xl"
        >
          Build Your Dream
          <br />
          <span className="text-gradient-mixed">Career with AI</span>
        </motion.h1>

        {/* Subheading */}
        <motion.p
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.25 }}
          className="mt-6 max-w-2xl text-lg text-muted-foreground md:text-xl"
        >
          Get a personalized career roadmap, track your progress, earn Forge Coins,
          level up, and discover opportunities — all powered by advanced AI.
        </motion.p>

        {/* ============================================
            Hero Input — Target Role
            ============================================ */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.4 }}
          className="mt-10 flex w-full max-w-xl flex-col gap-3 sm:flex-row"
        >
          <div className="relative flex-1">
            <Input
              type="text"
              placeholder="Enter your target job/role (e.g., Full-Stack Developer)"
              value={targetRole}
              onChange={(e) => setTargetRole(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && handleGenerate()}
              className="h-13 rounded-xl border-white/10 bg-white/[0.04] pl-5 pr-4 text-base text-foreground placeholder:text-muted-foreground/60 focus:border-cyan-accent/40 focus:ring-2 focus:ring-cyan-accent/20 transition-all"
            />
          </div>
          <Button
            onClick={handleGenerate}
            disabled={!targetRole.trim()}
            className="h-13 rounded-xl bg-gradient-to-r from-cyan-accent to-cyan-glow px-8 text-base font-semibold text-black hover:opacity-90 disabled:opacity-40 transition-all group"
          >
            Generate Roadmap
            <ArrowRight className="ml-2 h-4 w-4 transition-transform group-hover:translate-x-1" />
          </Button>
        </motion.div>

        {/* Trust badges */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.5, delay: 0.6 }}
          className="mt-5 flex items-center gap-3 text-sm text-muted-foreground/50"
        >
          <span>Free to start</span>
          <span>·</span>
          <span className="flex items-center gap-1">
            <ForgeCoinIcon size={14} />
            Earn Forge Coins
          </span>
          <span>·</span>
          <span>AI-generated in seconds</span>
        </motion.div>
      </section>

      {/* ============================================
          Features Grid
          ============================================ */}
      <section className="relative z-10 mx-auto max-w-6xl px-6 py-20">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.6 }}
          className="mb-14 text-center"
        >
          <h2 className="text-3xl font-bold tracking-tight md:text-4xl">
            Everything You Need to{" "}
            <span className="text-gradient-cyan">Succeed</span>
          </h2>
          <p className="mt-4 text-muted-foreground">
            A complete career acceleration toolkit, powered by artificial
            intelligence.
          </p>
        </motion.div>

        <motion.div
          variants={staggerContainer}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: "-50px" }}
          className="grid gap-6 sm:grid-cols-2"
        >
          {features.map((feature, i) => (
            <motion.div
              key={feature.title}
              variants={fadeUp}
              custom={i}
              whileHover={{ y: -4, transition: { duration: 0.2 } }}
              className="group relative overflow-hidden rounded-2xl border border-white/[0.06] bg-white/[0.02] p-7 transition-colors hover:border-white/[0.12]"
            >
              {/* Glow overlay */}
              <div
                className={`absolute inset-0 bg-gradient-to-br ${feature.gradient} opacity-0 transition-opacity group-hover:opacity-100`}
              />

              <div className="relative z-10">
                <div
                  className={`mb-4 inline-flex h-11 w-11 items-center justify-center rounded-xl bg-white/[0.06] ${feature.iconColor}`}
                >
                  <feature.icon className="h-5 w-5" />
                </div>
                <h3 className="mb-2 text-lg font-semibold text-foreground">
                  {feature.title}
                </h3>
                <p className="text-sm leading-relaxed text-muted-foreground">
                  {feature.description}
                </p>
              </div>
            </motion.div>
          ))}
        </motion.div>
      </section>

      {/* ============================================
          How It Works Section
          ============================================ */}
      <section className="relative z-10 mx-auto max-w-5xl px-6 py-20">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="mb-14 text-center"
        >
          <h2 className="text-3xl font-bold tracking-tight md:text-4xl">
            How It <span className="text-gradient-purple">Works</span>
          </h2>
          <p className="mt-4 text-muted-foreground">
            From goal to career in three simple steps.
          </p>
        </motion.div>

        <motion.div
          variants={staggerContainer}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true }}
          className="grid gap-8 md:grid-cols-3"
        >
          {[
            {
              step: "01",
              title: "Set Your Goal",
              desc: "Tell us your dream role — from Software Engineer to Data Scientist to UX Designer.",
            },
            {
              step: "02",
              title: "AI Generates Your Path",
              desc: "Our AI creates a detailed, phased roadmap with courses, projects, and milestones.",
            },
            {
              step: "03",
              title: "Track, Earn & Grow",
              desc: "Follow your roadmap, earn Forge Coins, level up, and land your dream opportunities.",
            },
          ].map((item, i) => (
            <motion.div
              key={item.step}
              variants={scaleIn}
              className="relative flex flex-col items-center text-center"
            >
              <div className="mb-5 flex h-16 w-16 items-center justify-center rounded-2xl border border-white/[0.06] bg-white/[0.03] text-2xl font-bold text-gradient-cyan">
                {item.step}
              </div>
              <h3 className="mb-2 text-lg font-semibold">{item.title}</h3>
              <p className="text-sm text-muted-foreground">{item.desc}</p>

              {/* Connector line */}
              {i < 2 && (
                <div className="absolute right-0 top-8 hidden h-px w-8 translate-x-full bg-gradient-to-r from-white/10 to-transparent md:block" />
              )}
            </motion.div>
          ))}
        </motion.div>
      </section>

      {/* ============================================
          CTA Section
          ============================================ */}
      <section className="relative z-10 mx-auto max-w-4xl px-6 py-20">
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          whileInView={{ opacity: 1, scale: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="relative overflow-hidden rounded-3xl border border-white/[0.06] bg-gradient-to-br from-cyan-accent/[0.06] to-purple-accent/[0.06] p-12 text-center"
        >
          {/* Glow */}
          <div className="absolute -top-[200px] left-1/2 h-[400px] w-[400px] -translate-x-1/2 rounded-full bg-cyan-accent/[0.08] blur-[80px]" />

          <div className="relative z-10">
            <h2 className="text-3xl font-bold md:text-4xl">
              Ready to Start Your Journey?
            </h2>
            <p className="mt-4 text-muted-foreground">
              Join thousands of professionals accelerating their careers with AI.
            </p>
            <div className="mt-4 flex items-center justify-center gap-2 text-sm text-amber-400/70">
              <ForgeCoinIcon size={16} />
              <span>Earn 100 Forge Coins welcome bonus!</span>
            </div>
            <Link href="/auth/signup">
              <Button className="mt-8 h-12 rounded-xl bg-gradient-to-r from-cyan-accent to-cyan-glow px-10 text-base font-semibold text-black hover:opacity-90 transition-opacity group">
                Get Started Free
                <ChevronRight className="ml-1 h-4 w-4 transition-transform group-hover:translate-x-1" />
              </Button>
            </Link>
          </div>
        </motion.div>
      </section>

      {/* ============================================
          Footer
          ============================================ */}
      <footer className="relative z-10 border-t border-white/[0.06] px-6 py-10">
        <div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-4 md:flex-row">
          <div className="flex items-center gap-2">
            <div className="flex h-7 w-7 items-center justify-center rounded-md bg-gradient-to-br from-cyan-accent to-purple-accent">
              <Zap className="h-4 w-4 text-black" />
            </div>
            <span className="text-sm font-semibold text-muted-foreground">
              Careerly AI
            </span>
          </div>
          <p className="text-xs text-muted-foreground/50">
            © {new Date().getFullYear()} Careerly AI. All rights reserved.
          </p>
          <div className="flex items-center gap-4">
            <a
              href="#"
              className="text-muted-foreground/50 transition-colors hover:text-foreground"
            >
              <svg className="h-4 w-4" fill="currentColor" viewBox="0 0 24 24"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
            </a>
            <a
              href="#"
              className="text-muted-foreground/50 transition-colors hover:text-foreground"
            >
              <svg className="h-4 w-4" fill="currentColor" viewBox="0 0 24 24"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/></svg>
            </a>
          </div>
        </div>
      </footer>
    </div>
  );
}
